### ISSUE TITLE
Tor Browser: highest setting users: should have alert

### ISSUE THREAD

**Issue by okaysoraya** [EFForg/starttls-frontend#150] opened 2018-06-11 17:19 UTC
I did some testing with the highest safety setting on Tor Browser (JS disabled, images disabled, audio/video click to play).

Since the tool won't work for these users, could we have a notification saying that they won't be able to take advantage of the site since it uses javascript? Otherwise the results that it spits out look like this.

![screen shot 2018-06-11 at 10 17 01 am](https://user-images.githubusercontent.com/16709499/41246748-dd9505de-6d60-11e8-8039-a89afdba2306.png)

**Comment by vbrown608** [comment] 2019-01-02 16:17
Duplicate of https://github.com/EFForg/starttls-frontend/issues/223

**Closed by vbrown608** 2019-01-02 16:17 UTC
Labels: no-js, question
